[build]
  functions = "dashboard/netlify/functions"

[[redirects]]
  from = "/dashboard"
  to = "/dashboard/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
